# Lab 2: Implementing Apriori Algorithm

In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from IPython.display import display_html

In [2]:
def toy_dataset():
    data = [
        ["Milk", "Onion", "Nutmeg", "Kidney Beans", "Eggs", "Yogurt"],
        ["Dill", "Onion", "Nutmeg", "Kidney Beans", "Eggs", "Yogurt"],
        ["Milk", "Apple", "Kidney Beans", "Eggs"],
        ["Milk", "Unicorn", "Corn", "Kideny Beans", "Yogurt"],
        ["Corn", "Onion", "Onion", "Kidney Beans", "Ice Cream", "Eggs"]
    ]
    print("Do you want to view raw data?")
    choice = input()
    if choice == 'yes':
        print("Raw Data:")
        print(data)
    te = TransactionEncoder()
    te_ary = te.fit(data).transform(data)
    df = pd.DataFrame(te_ary, columns = te.columns_)
    print("Do you want to view the Encoded data?")
    choice = input()
    if choice == 'yes':
        print("Encoded Data:")
        display_html(df)
    return df

In [3]:
def frequent_itemset(data):
    print("Enter the value of minimum support threshold:")
    support = float(input())
    frequent_itemsets = apriori(data, min_support = support, 
                                use_colnames = True)
    print("Do you want to view frequent itemsets generated by Apriori?")
    choice = input()
    if choice == 'yes':
        print("Frequent itemset")
        display_html(frequent_itemsets)
    return frequent_itemsets

In [4]:
def association_rule(frequent_itemsets):
    print("Enter your choice")
    choice = input()
    if choice == 'confidence':
        print("Enter minimum confidence threshold value")
        min_confidence = float(input())
        rule = association_rules(frequent_itemsets, metric='confidence', 
                                 min_threshold=min_confidence)
    elif choice == 'lift':
        print("Enter minimum lift threshold value")
        min_lift = float(input())
        rule = association_rules(frequent_itemsets, metric = 'lift', 
                                 min_threshold=min_lift)
    print("Do you want to view the learned association rules?")
    choice = input()
    if choice == 'yes':
        display_html(rule.drop(['leverage', 'conviction'], axis = 1))
    else:
        quit()

In [5]:
def main():
    data = toy_dataset()
    frequent_itemsets = frequent_itemset(data)
    association_rule(frequent_itemsets)

**Output:**

In [8]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from IPython.display import display_html

def toy_dataset():
    data = [
        ["Milk", "Onion", "Nutmeg", "Kidney Beans", "Eggs", "Yogurt"],
        ["Dill", "Onion", "Nutmeg", "Kidney Beans", "Eggs", "Yogurt"],
        ["Milk", "Apple", "Kidney Beans", "Eggs"],
        ["Milk", "Unicorn", "Corn", "Kidney Beans", "Yogurt"],
        ["Corn", "Onion", "Onion", "Kidney Beans", "Ice Cream", "Eggs"]
    ]
    print("Do you want to view raw data?")
    choice = input()
    if choice == 'yes':
        print("Raw Data:")
        print(data)
    te = TransactionEncoder()
    te_ary = te.fit(data).transform(data)
    df = pd.DataFrame(te_ary, columns = te.columns_)
    print("Do you want to view the Encoded data?")
    choice = input()
    if choice == 'yes':
        print("Encoded Data:")
        display_html(df)
    return df

def frequent_itemset(data):
    print("Enter the value of minimum support threshold:")
    support = float(input())
    frequent_itemsets = apriori(data, min_support = support, 
                                use_colnames = True)
    print("Do you want to view frequent itemsets generated by Apriori?")
    choice = input()
    if choice == 'yes':
        print("Frequent itemset")
        display_html(frequent_itemsets)
    return frequent_itemsets

def association_rule(frequent_itemsets):
    print("Enter your choice")
    choice = input()
    if choice == 'confidence':
        print("Enter minimum confidence threshold value")
        min_confidence = float(input())
        rule = association_rules(frequent_itemsets, metric='confidence', 
                                 min_threshold=min_confidence)
    elif choice == 'lift':
        print("Enter minimum lift threshold value")
        min_lift = float(input())
        rule = association_rules(frequent_itemsets, metric = 'lift', 
                                 min_threshold=min_lift)
    print("Do you want to view the learned association rules?")
    choice = input()
    if choice == 'yes':
        display_html(rule.drop(['leverage', 'conviction'], axis = 1))
    else:
        quit()

def main():
    data = toy_dataset()
    frequent_itemsets = frequent_itemset(data)
    association_rule(frequent_itemsets)

main()

Do you want to view raw data?
yes
Raw Data:
[['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'], ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'], ['Milk', 'Apple', 'Kidney Beans', 'Eggs'], ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'], ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice Cream', 'Eggs']]
Do you want to view the Encoded data?
yes
Encoded Data:

,Apple,Corn,Dill,Eggs,Ice Cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

Enter the value of minimum support threshold:
0.6
Do you want to view frequent itemsets generated by Apriori?
yes
Frequent itemset

,support,itemsets
0,0.8,(Eggs)
1,1.0,(Kidney Beans)
2,0.6,(Milk)
3,0.6,(Onion)
4,0.6,(Yogurt)
5,0.8,"(Eggs, Kidney Beans)"
6,0.6,"(Onion, Eggs)"
7,0.6,"(Kidney Beans, Milk)"
8,0.6,"(Onion, Kidney Beans)"
9,0.6,"(Kidney Beans, Yogurt)"
10,0.6,"(Onion, Eggs, Kidney Beans)"

Enter your choice
confidence
Enter minimum confidence threshold value
0.7
Do you want to view the learned association rules?
yes

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
0,(Eggs),(Kidney Beans),0.8,1.0,0.8,1.00,1.00
1,(Kidney Beans),(Eggs),1.0,0.8,0.8,0.80,1.00
2,(Onion),(Eggs),0.6,0.8,0.6,1.00,1.25
3,(Eggs),(Onion),0.8,0.6,0.6,0.75,1.25
4,(Milk),(Kidney Beans),0.6,1.0,0.6,1.00,1.00
5,(Onion),(Kidney Beans),0.6,1.0,0.6,1.00,1.00
6,(Yogurt),(Kidney Beans),0.6,1.0,0.6,1.00,1.00
7,"(Onion, Eggs)",(Kidney Beans),0.6,1.0,0.6,1.00,1.00
8,"(Onion, Kidney Beans)",(Eggs),0.6,0.8,0.6,1.00,1.25
9,"(Eggs, Kidney Beans)",(Onion),0.8,0.6,0.6,0.75,1.25
10,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.00,1.25
11,(Eggs),"(Onion, Kidney Beans)",0.8,0.6,0.6,0.75,1.25